version: '3.8'

services:
  ca-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ca-api
    working_dir: /app
    volumes:
      - .:/app
      - ${CA_BASE_PATH:-/data}:/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: ["./docker-entrypoint.sh"]

volumes:
  ca_data:
    driver: local

networks:
  ca-network:
    driver: bridge 